### ISSUE TITLE
火狐浏览器，同步书签，报错，总是缺少一个书签栏，其他两个浏览器没有问题。

### ISSUE THREAD

**Issue by Totoro-jam** [dudor/BookmarkHub#10]
![图片](https://user-images.githubusercontent.com/62227038/124356995-d5a5c180-dc4b-11eb-822b-8922a135c809.png)

**Comment by cuoo** [comment]
一样的问题，只下载了几个书签下来。
![20210710170921_371_130](https://user-images.githubusercontent.com/28379772/125158211-092fa100-e1a2-11eb-8e98-94ea3e5233f5.png)

**Comment by dudor** [comment]
@cuoo @Totoro-jam 这个bug是firefox无法创建chrome协议格式的书签导致的，目前firefox只能跳过创建这种格式书签了。
