### ISSUE TITLE
使用过程中很奇怪地出现了CPU和内存的异常占用

### ISSUE THREAD

**Issue by Canary-InTheSky** [dudor/BookmarkHub#14]
![Snipaste_2021-07-20_23-56-56](https://user-images.githubusercontent.com/46470696/126361080-996f1525-1b4b-45b6-8669-6f137f5ea245.png)

就是和平时一样正常的在用浏览器，突然遇到了浏览器卡死，笔记本风扇起飞的情况，经过几次排查，根据进程ID查到是插件突然占用了大量的CPU和内存资源，截图所示，出现该问题时浏览器的全部窗口已经卡死，任务管理器中显示了异常的占用。

在手动上传书签后，也有时在浏览器正常使用过程中，都出现了该问题，完全结束浏览器进程后重启浏览器，再通过前面两种方式依旧会触发该情况，但该问题在重启电脑后却消失了。

浏览器是：Microsoft Edge 91.0.864.70和91.0.864.71(出问题的过程中自动更新了)
书签数量大概是4050左右

用了也算有段时间了，这种情况也就出现了今天这一次。

**Comment by bestpika** [comment]
請用瀏覽器內建的工作管理員看不要用系統的工作管理員

**Comment by bestpika** [comment]
使用率看起來不是在 BookmarkHub 上啊

**Comment by Canary-InTheSky** [comment]
> 使用率看起來不是在 BookmarkHub 上啊

出问题的时候，浏览器内建管理器也卡死不动了，完全看不到变化，也没法操作，而且浏览器内建管理器的进程ID就是系统任务管理器里的PID。

这两天用着也没出问题…具体什么情况还是不太清楚

**Comment by dudor** [comment]
@Canary-InTheSky 
请问你用的是Edge商店的0.0.2这个版本吗。这个版本有些输出日志的代码我忘记删掉了，可能会在下载大量书签的时候产生大量日志，引起CPU异常。我晚上把Edge商店中的程序更新到0.0.3版本，审核通过后你再试试。或者你可以在Edge中安装chrome商店的0.0.3版本试试。

**Comment by Canary-InTheSky** [comment]
> @Canary-InTheSky
> 请问你用的是Edge商店的0.0.2这个版本吗。这个版本有些输出日志的代码我忘记删掉了，可能会在下载大量书签的时候产生大量日志，引起CPU异常。我晚上把Edge商店中的程序更新到0.0.3版本，审核通过后你再试试。或者你可以在Edge中安装chrome商店的0.0.3版本试试。

确实是edge的版本，但是我好像只用了上传操作…而且用到现在也只出现过那一天的问题，重启电脑解决了之后，这两天也没有再出现。

**Comment by dudor** [comment]
哦，那只能再跟踪看看了，贴图上的数据看着都很正常。
另外我看你安装的扩展有点多，会不会是别的引起的

**Comment by Canary-InTheSky** [comment]
> 哦，那只能再跟踪看看了，贴图上的数据看着都很正常。
> 另外我看你安装的扩展有点多，会不会是别的引起的

贴图里浏览器的任务管理器是已经卡死的，所以内容都还是正常的。然后根据系统的任务管理器找到的对应的进程ID不是别的插件……
我继续看看，感觉上因为重启电脑才能好，所以这事儿说不定是系统的锅。

**Comment by Hiddensu** [comment]
我的也是，CPU占用高，风扇狂转。

**Comment by dudor** [comment]
@Hiddensu 你的书签数量多少，Edge版本号多少。我也多用用Edge，之前主要在用Chrome。

**Comment by Hiddensu** [comment]
> @Hiddensu 你的书签数量多少，Edge版本号多少。我也多用用Edge，之前主要在用Chrome。

我用的是cent百分，书签应该有两三千个。

**Comment by dudor** [comment]
@Hiddensu 当时有没有看到浏览器任务管理器中的bookmarkhub插件的CPU、内存占用情况？
另外"cent百分"是什么?

**Comment by Canary-InTheSky** [comment]
很久没遇到了，大概率是当时其它什么操作导致的
