### ISSUE TITLE
上传错误not found

### ISSUE THREAD

**Issue by zhukm** [dudor/BookmarkHub#17]
请问这是什么原因，怎么解决？kiwi浏览器

**Comment by dudor** [comment]
是不是gist ID 没填对，或者token 没有勾选gist权限
@zhukm

**Comment by zhukm** [comment]
感谢大佬，是token里的gist，原来不知道要勾选，create gist，成功，非常感谢！

**Comment by zhukm** [comment]
感谢作者指导，成功使用。
