### ISSUE TITLE
书签过大后 github gists content返回不全导致无法同步书签

### ISSUE THREAD

**Issue by buyaoyongroot** [dudor/BookmarkHub#2]
Thanks to the author, this is a good project.
### 书签过大无法使用
书签过大有7000多url，经测试，转json上传没问题，但是下载同步的时候
github gists content返回不全 会导致无法同步书签
测试后 不是书签内容的问题，json是完整的，但是github gists content在775235~784850字节后就不显示了
这样json.parse肯定是不能用的
看返回值发现 可以通过二次请求raw_url参数来获取content，而不是直接使用content字段

### gist传输内容应该加密，不应该直接存储JSON明文
还有 gist 是知道url就可以打开的，所以最好在配置项里面能不能加aes256加密，这样可以防止中间人
不然一些隐私的地址 还是会有泄露风险

**Comment by dudor** [comment]
@buyaoyongroot 
>书签过大无法使用
这几天我修复下
>gist传输内容应该加密，不应该直接存储JSON明文
访问gist用的是https 协议通信，安全性还是有一定保障的
导入导出等后期会加上，firefox和chrome用的是一套源代码，你可以编译下试试
