### ISSUE TITLE
您好,功能很好用,也非常方便,但是有个小问题,清空所有收藏夹很容易造成困扰

### ISSUE THREAD

**Issue by duzidengdaizz** [dudor/BookmarkHub#3]
chrome的收藏集又被不知道哪个设备误删了,已经同步了..丢了一部分收藏夹 所以搜索了一下插件发现了这个.尝试了一下挺好用.也非常方便.备份跟下载都非常方便..
下面的清空就有点难受了.不小心点上 不确认直接清空了.
能否在下个版本隐藏起来或者放到二级菜单增加确认呢.感谢

**Comment by dudor** [comment]
@duzidengdaizz 好的，谢谢反馈，下个版本我优化下
