### ISSUE TITLE
有时候会插件自己突然清空我的书签

### ISSUE THREAD

**Issue by my5d2** [dudor/BookmarkHub#35]
有时候会自己突然清空我的书签，在我没点清空我的书签的情况下.

**Comment by This-is-sdz** [comment]
好像只在edge上会出现

**Comment by dudor** [comment]
有没有可能是edge自带的同步服务清空的，edge我用过一段时间，暂时还没遇到过这种情况

**Comment by gitsdz** [comment]
好像不是，关闭浏览器自带的同步也会无缘无故清空我的书签，以前从来没有这种情况。

**Comment by dudor** [comment]
你的edge是哪个版本的，有没有安装其他的书签插件？或者你把浏览器重新安装下试试。你说的这种情况我都不知道该如何去排查。😂

**Comment by my5d2** [comment]
我终于排查出来谁是罪魁祸首了,是iCloud书签,谢谢大佬
