### ISSUE TITLE
能否同步 Favicon?

### ISSUE THREAD

**Issue by xianghongai** [dudor/BookmarkHub#43]
目前同步不带 Favicon，索引时不是很方便。。。

**Comment by dudor** [comment]
@xianghongai 
目前好像同步不了，主要是浏览器没有提供fav相关的接口。

**Comment by xianghongai** [comment]
我有一个自行手动备份浏览器 Favicon 的方法，，Windows 平台：

- Firefox：`%APPDATA%\Mozilla\Firefox\Profiles\` 中用户配置目录中 的 `favicons.sqlite` 文件；
- Chrome：`%LOCALAPPDATA%\Google\Chrome\User Data\Default` 目录下的 `Favicons` 文件；
- Edage：`%LOCALAPPDATA%\Microsoft\Edge\User Data\Default` 目录下的 `Favicons` 文件。

存储浏览器 Favicon 的是 SQLite 目录，回头写一个同步各 icon 的 SQL。
