### ISSUE TITLE
未来chrome会下架MV2的插件，大佬是否会更新MV3版本呢

### ISSUE THREAD

**Issue by mlc2743** [dudor/BookmarkHub#72]
未来chrome会下架MV2的插件，大佬是否会更新MV3版本呢

**Comment by dudor** [comment]
@mlc2743 一定会的，mv3版本会有很大变化。

**Comment by mlc2743** [comment]
> @mlc2743 一定会的，mv3版本会有很大变化。

感谢回复，期待新版本的到来。加油！！！

**Comment by Lazyjason** [comment]
> @mlc2743 一定会的，mv3版本会有很大变化。

您好，我现在使用的Chrome Beta版本 127.0.6533.57 已经开始提示扩展程序将很快不受支持了，期待可以更新V3版本的扩展。谢谢您！

**Comment by dudor** [comment]
@Lazyjason @mlc2743 已更新MV3
