### ISSUE TITLE
would really like autosync everytime I add/change bookmarks😀

### ISSUE THREAD

**Issue by thivyanth** [dudor/BookmarkHub#76]

**Comment by thivyanth** [comment]
did you try doing it periodically and syncs when there are changes?

**Comment by thivyanth** [comment]
@william20210206

**Comment by william20210206** [comment]
> did you try doing it periodically and syncs when there are changes?

I just upload the bookmarks manually ,everytime the red exclamation mark shown.

**Comment by william20210206** [comment]
> @william20210206

Sorry , English is not my native language, and I did't noticed the message for a long time althong I suffering Github offen.

**Comment by william20210206** [comment]
> @william20210206

Sorry , English is not my native language, and I did't noticed the message for a long time althong I surf Github offen.

**Comment by william20210206** [comment]
I'm developing it JavaScript now, but my extension is twice slower than this one,I don't know why, I'm trying to find some solution now.

**Comment by fcoj-IT** [comment]
I was just able to configure it... then I realized the project stopped in 2021... I hope someone is able to continue it... I think the main two tings would be  Automatically sync bookmarks and Merging bookmark. I think sharing would be useless.

**Comment by thivyanth** [comment]
I've uploaded the feature here: 😄
- [commit](https://github.com/thivyanth/BookmarkHub/commit/e43a1498f5e2688bcb1b7b9f5d223e85f9fa94a0)
- [branch](https://github.com/thivyanth/BookmarkHub/tree/main)
