### ISSUE TITLE
软件已经不再更新了吗

### ISSUE THREAD

**Issue by taoqixfz** [dudor/BookmarkHub#82]
主用Firefox Nightly，在Firefox Nightly无法上传提示报错。
于是把Firefox Nightly书签导出html后导入到Chrome上传，Chrome上传成功了。
换到edge浏览器无法下载提示报错，三款浏览器插件均在各自的插件商店下载。

**Comment by dudor** [comment]
@taoqixfz 明天我测试下最新版浏览器。目前这个版本v0处于维护状态，会修复严重bug。新功能会发布新版本。

**Comment by dudor** [comment]
@taoqixfz 刚测试Firefox Nightly 135.0a1 (2024-12-20) (64-bit)，上传下载正常，建议你检查下网络代理环境是否有问题。
