### ISSUE TITLE
大佬，0.0.5无法安装啊，显示无法加载清单。

### ISSUE THREAD

**Issue by philboycn** [dudor/BookmarkHub#83]
错误信息：
清单文件缺失或不可读取
无法加载清单。

麻烦大佬看看，谢谢！

**Comment by dudor** [comment]
@philboycn 浏览器是哪个版本

**Comment by philboycn** [comment]
> @philboycn 浏览器是哪个版本

Chrome 131.0.6778.109。然后360极速浏览器也是chrome内核的，122.0.6261.95版本，也是一样的错误。

**Comment by dudor** [comment]
@philboycn 我刚下载的chrome 131.0.6778.205（正式版本）,上传下载没问题，你卸载重新安装下试试。

**Comment by philboycn** [comment]
> @philboycn 我刚下载的chrome 131.0.6778.205（正式版本）和Edge 131.0.2903.112 (正式版本) (64 位)，上传下载没问题。测试了360极速版不行，好像一直都存在兼容问题。

chrome搞好了，谢谢大佬。360不行，但0.0.4版本360是OK的。就只有chrome用0.0.5，360用0.0.4啦，哈哈。
